//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Isle.Converters.Roslyn.Analyzers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Isle.Converters.Roslyn.Analyzers.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured names should be unique..
        /// </summary>
        internal static string CapturedNameMustBeUniqueDescription {
            get {
                return ResourceManager.GetString("CapturedNameMustBeUniqueDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured name &apos;{0}&apos; is already used in this message template..
        /// </summary>
        internal static string CapturedNameMustBeUniqueMessageFormat {
            get {
                return ResourceManager.GetString("CapturedNameMustBeUniqueMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured name is not unique.
        /// </summary>
        internal static string CapturedNameMustBeUniqueTitle {
            get {
                return ResourceManager.GetString("CapturedNameMustBeUniqueTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured names should be convertible to valid C# identifiers..
        /// </summary>
        internal static string CapturedNameMustBeValidIdentifierDescription {
            get {
                return ResourceManager.GetString("CapturedNameMustBeValidIdentifierDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured name &apos;{0}&apos; cannot be converted to a valid C# identifier..
        /// </summary>
        internal static string CapturedNameMustBeValidIdentifierMessageFormat {
            get {
                return ResourceManager.GetString("CapturedNameMustBeValidIdentifierMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captured name cannot be converted to a valid C# identifier.
        /// </summary>
        internal static string CapturedNameMustBeValidIdentifierTitle {
            get {
                return ResourceManager.GetString("CapturedNameMustBeValidIdentifierTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit names should be valid C# identifiers..
        /// </summary>
        internal static string ExplicitNameMustBeValidIdentifierDescription {
            get {
                return ResourceManager.GetString("ExplicitNameMustBeValidIdentifierDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit name &apos;{0}&apos; is not a valid C# identifier..
        /// </summary>
        internal static string ExplicitNameMustBeValidIdentifierMessageFormat {
            get {
                return ResourceManager.GetString("ExplicitNameMustBeValidIdentifierMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit name must be a valid C# identifier.
        /// </summary>
        internal static string ExplicitNameMustBeValidIdentifierTitle {
            get {
                return ResourceManager.GetString("ExplicitNameMustBeValidIdentifierTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name passed to the Named method should be a constant..
        /// </summary>
        internal static string ExplicitNameShouldBeConstantDescription {
            get {
                return ResourceManager.GetString("ExplicitNameShouldBeConstantDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-constant name is passed to the Named method..
        /// </summary>
        internal static string ExplicitNameShouldBeConstantMessageFormat {
            get {
                return ResourceManager.GetString("ExplicitNameShouldBeConstantMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit name is not a constant.
        /// </summary>
        internal static string ExplicitNameShouldBeConstantTitle {
            get {
                return ResourceManager.GetString("ExplicitNameShouldBeConstantTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit name should not have leading or trailing white spaces..
        /// </summary>
        internal static string ExplicitNameShouldNotHaveWhiteSpacesDescription {
            get {
                return ResourceManager.GetString("ExplicitNameShouldNotHaveWhiteSpacesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit name &apos;{0}&apos; has leading or trailing white spaces..
        /// </summary>
        internal static string ExplicitNameShouldNotHaveWhiteSpacesMessageFormat {
            get {
                return ResourceManager.GetString("ExplicitNameShouldNotHaveWhiteSpacesMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explicit name has leading or trailing white spaces.
        /// </summary>
        internal static string ExplicitNameShouldNotHaveWhiteSpacesTitle {
            get {
                return ResourceManager.GetString("ExplicitNameShouldNotHaveWhiteSpacesTitle", resourceCulture);
            }
        }
    }
}
